var GAME_LEVELS = [
  ["                                                                                ",
   "                                            xxx                                 ",
   "                                            x!x                                 ",
   "                                            xvx                                 ",
   "                                                                   y            ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                                   xx      xx    xx!xx          ",
   "           y   y                 y       xxxxxx                  x!!!x          ",
   "          yy  yyy                     f                          xx!xx          ",
   "          yyyyyyy              xxxxx  f                           xvx           ",
   "                                           y                                xx  ",
   "  xx                                                                         x  ",
   "  x                                      xxxxx                          f    x  ",
   "  x                         xxx    y                                   f   o x  ",
   "  x                                              xxx                  f      x  ",
   "  x  @          f                 xxx                            xxxxx       x  ",
   "  xxxxxxxxxxxx     xxxxxxxx                                xxxxxxx   xxxxxxxxx  ",
   "             x!!!!!x      x                                x                    ",
   "             x!!!!!x      x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "             xxxxxxx      x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                               xxxx       xxx                                   ",
   "                                         x     x!!x                                             ",
   "                                         x     xvvx               xxx                           ",
   "                          o              x                                                      ",
   "                         xxxxxxxxxxxxxxxxx                     f                                ",
   "                         x       x                         xxxxxxxxxx                           ",
   "                         x       x                                                              ",
   "                         x!!!!!!!x                                                              ",
   "                         x!!!!!!!x                   xxxxx                                      ",
   "     @    o              x!!!!!!!x                                                              ",
   "   xxxxxxxxxxxxxxx   xxxxxxxvvxxxx        xxxxx                                        xx       ",
   "                 x   x                                                                  x       ",
   "                 x   x                                                                  x       ",
   "                 x                   xxx                                                x       ",
   "                 x                           xxxxxxxxxxx                                x       ",
   "!!!!!!!!!!!!!!!!!x       xxxxxxxxx                                                      x       ",
   "!!!!!!!!!!!!!!!!!x     x                                                 xxxxxxxxxxxxxxxx       ",
   "!!!!!!!!!!!!!!!!!x                     f xxxxxxxxxxxxxxxxxxxxxxx  fff   xx                      ",
   "!!!!!!!!!!!!!!!!!x                    f  xx                     xx!!!!!xx                       ",
   "!!!!!!!!!!!!!!!!!xxxxxxx             f   xx                       xxxxxxx                       ",
   "!!!!!!!!!!!!!!!!!!!!!!!!xx   f   xxxxxxxxxx                                                     ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx!!!!!!!!!x                                                     ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                                     "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                f                             ",
   "                                          xxxxxvvxx                            xxx                            ",
   "                                          x                                   x!!!x                           ",
   "                                          x                 xxxxxxxxxxxx       xxx                            ",
   "                                          x          f              x      f                                  ",
   "                                          x         xxxxx           x      xxx                             x  ",
   "                                          x          x              x     x!!!x                            x  ",
   "                                          xxx        x              x      xxx                             x  ",
   "                                          x          x              x                                      x  ",
   "                                          x        xxx              x                                      x  ",
   "                                          x          x              x       xxxxxxxxxxxxxxxxx              x  ",
   "                                          xxx        x              x                                      x  ",
   "                                          x          x              x                                      x  ",
   "                                          x        xxx!!!!!!!!!!!!!!x                                      x  ",
   "                                          x          x!!!!!!!!!!!!!!x                                      x  ",
   "                             xxxxxxxxxxxxxxx         x!!!!!!!!!!!!!!x                                      x  ",
   "                             x!!!!!!!!!!!!!x         x!!!!!!!!!!!!!!x                                      x  ",
   "                             x!!!!!!!!!!!!!x      xxxxxxxvvxxxxxxxxxxxxxxx             f                   x  ",
   "                             xxxvvxxxxxvvxxxxx                           x            xxx     xxxxxxx      x  ",
   "  xxx                         x     x      x                             x           x!!!xfffffffffffffffxxx  ",
   "  x x                         x    xxx     x                             x            xxx                x x  ",
   "  x                           x    xvx     xxxxxx                        x                                 x  ",
   "  x                           x                                          x                                 x  ",
   "  x                           x                        xxxxx             xxxxx                             x  ",
   "  x               f                                                      x                xxx                 ",
   "  x              xxx                           xxx              xxx      x         xxx           o            ",
   "  x             xxxxx         xx                                        xxx       x!!!x          x         x  ",
   "  x            xxxxxxx        x    xxx                                  x x        xxx          xxx        x  ",
   "  x           xxxxxxxxx       xxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx xx!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!x  ",
   "  x o    @   xxxxxxxxxxx      x           x!!!!!!!!!!!!!!!!!!!!!!!!!!!xx   xx!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                          ",
   "                                                                                                          ",
   "                                                                                                          ",
   "                                                                                                          ",
   "                                                                                                          ",
   "        @                                                                                      o          ",
   "      xxxxx xxxxx xx   x xxxxx  xxxxx    x    xxxxx x   x x        x    xxxxx x xxxxx xx   x xxxxx        ",
   "      x     x   x x x  x x      x  x    x x     x   x   x x       x x     x   x x   x x x  x x            ",
   "      x     x   x x  x x x  xxx x x    x x x    x   x   x x      x x x    x   x x   x x  x x   x          ",
   "      xxxxx xxxxx x   xx xxxxx  x   x x     x   x   xxxxx xxxxx x     x   x   x xxxxx x   xx xxxxx        ",
   "                                                                                                          ",
   "                                                                                                          ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
